---
title:                                  Auf der Spur
tagline:                                Die ARD Ermittlerkrimis

date:                                   2024-09-10
#last_modified:                         2024-09-10

description: >
                                        Mysteriöse Morde und kuriose Kriminalfälle im Fadenkreuz. Ob Kommissar-Genie,
                                        Privatdetektivin, Profilerin oder Hobbyschnüffler: Im Krimi-Podcast begeben
                                        sich Ermittler im Kampf gegen das Verbrechen auf die Spurensuche.
keywords: >
                                        WDR 5, Sherlock Holmes, Detektivgeschichten,
                                        Hörbuch

categories:                             [ Audio ]
tags:                                   [ Hörbuch, Sherlock Holmes ]

image:
  path:                                 //daserste.de/sammlung-image-140~_type-at_ratio-1x1_width-1280_06a204.jpg
  width:                                1920
  height:                               1200

tts:                                    true
fab_menu_id:                            open_toc                                # default
personalization:                        false
comments:                               false

regenerate:                             false
permalink:                              /pages/public/audio/radioplay/auf_der_spur/

resources:                              [ amplitudejs ]
resource_options:
  - attic:
      opacity:                          .6
      padding_top:                      550
      slides:
        - url:                          //daserste.de/sammlung-image-140~_type-at_ratio-1x1_width-1280_06a204.jpg
          alt:                          Die ARD Ermittlerkrimis
          badge:
            type:                       unsplash
            author:                     ARD
            href:                       //ardaudiothek.de/sendung/auf-der-spur-die-ard-ermittlerkrimis/94582432/
---

// Page Initializer
// =============================================================================
// Enable the Liquid Preprocessor
:page-liquid:

// Set (local) page attributes here
// -----------------------------------------------------------------------------
// :page--attr:                         <attr-value>
:time-num--string:                      50+
:time-de--string:                       Minuten
:time-de--description:                  Audiozeit

//  Load Liquid procedures
// -----------------------------------------------------------------------------
{% capture load_attributes %}themes/{{site.template.name}}/procedures/global/attributes_loader.proc{%endcapture%}

// Load page attributes
// -----------------------------------------------------------------------------
{% include {{load_attributes}} scope="global" %}

// Page content
// ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
[role="dropcap"]
Mysteriöse Morde und kuriose Kriminalfälle im Fadenkreuz. Ob Kommissar-Genie,
Privatdetektivin, Profilerin oder Hobbyschnüffler: Im Krimi-Podcast begeben
sich Ermittler im Kampf gegen das Verbrechen auf die Spurensuche.

[subs=attributes]
++++
<div class="video-title">
  <i class="mdi mdi-gray mdi-clock-time-five-outline mdi-24px mr-2"></i>
  {time-num--string} {time-de--string} {time-de--description}
</div>
++++

// Include sub-documents (if any)
// -----------------------------------------------------------------------------
// See: https://www.ardaudiothek.de/sendung/auf-der-spur-die-ard-ermittlerkrimis/94582432/

Seit Sommer 2023 erscheint jedoe Woche, jeweils am Diestag, ein neuer
Krininamfall. Auf dieser Seite finden Sie eine Auswahl der Ermittler des
Podcasts und ihrer Fälle. Alle Episoden des Podcasts finden Sie unter
link://ardaudiothek.de/sendung/auf-der-spur-die-ard-ermittlerkrimis/94582432/[Die ARD Ermittlerkrimis, {browser-window--new}].

Viel Spaß beim Zuhören.


[role="mt-5"]
== Die Detektivinnen

lorem:sentences[5]

[role="mt-4"]
=== Fariza Nasri

Der Autor der Krimi-Reihe *Oberkommissarin Nasri und Ex-Mordermittler Franck*
ist _Friedrich Ani_.

Fariza Nasri ist eine Oberkommissarin, eine nüchterne und taffe Persönlichkeit
die ihren Beruf ernst nimmt. In diesen Krimis ermittelt sie zusammen mit dem
Ex-Mordermittler _Jakob Franck_.

Die Fälle sind in einen düsteren und kleinbürgerlichen Milieu angesiedelt
und behandeln Mordfälle in der Gegend von München. Die Hörspiele zeichnen
sich durch sorgfältige Ermittlungsarbeit und überraschende Lösungen aus.
Gelegentlich gibt es persönliche Kommentare von Nasri, die Einblicke in ihre
Gedankenwelt geben.

[role="mt-4"]
=== Melitta Frankenberg

Die Autorin der **Melitta und Stern**-Reihe ist _Katja Röder_.

_Melitta Frankenberg_ hat das Asperger-Syndrom. Diese Besonderheit ist in ihren
Ermittlungen sowohl ein Hindernis als auch eine Hilfe. Ihr Asperger ermöglicht
ihr ein besonders schnelles und analytisches Denken, kann aber gleichzeitig
Schwierigkeiten in der sozialen Kommunikation mit sich bringen.

Die Krimis spielen im fränkischen Raum, insbesondere in und um Bamberg. Die
Fälle drehen sich um regionale Besonderheiten und manchmal auch um die
Vergangenheit der Region. Ihre Fälle ermittelt Melitta zusammen mit ihrem
*kleinkriminellen* Freund _Anton Stern_.

[role="mt-4"]
[[bloemke-und-huppertz]]
=== Helga Bloemke und Käthe Huppertz

Helga Bloemke und Käthe Huppertz sind zwei Freundinnen, die auf humorvolle
und oft unkonventionelle Weise Kriminalfälle lösen. Ihre Geschichten sind
in einem rheinischen Milieu angesiedelt und zeichnen sich durch ihren
charmanten und humorvollen Ton aus.

Käthe Huppertz wird als die unternehmungslustigere und initiativere der
beiden dargestellt, während Helga Bloemke eher die bedächtigere und manchmal
etwas zögerliche Partnerin ist. Gemeinsam bilden sie jedoch ein unschlagbares
Team.

Die Hörspiele werden von den Autorinnen _Maria Franziska Schüller_ und
_Cornelia Walter_ geschrieben und erfreuen sich großer Beliebtheit.


[role="mt-5"]
== Die Detektive

[role="mt-4"]
lorem:sentences[5]

[role="mt-4"]
=== Commissario Brunetti

Commissario _Guido Brunetti_ ist die Hauptfigur in einer Reihe von Kriminal
Romanen der amerikanischen Autorin _Donna Leon_, die in Venedig spielen.
In den Romanen ist Brunetti ein Kriminalkommissar bei der italienischen
Staatspolizei, der in Venedig stationiert ist.

Die Krimi-Reihe begann im Jahr 1992 mit dem Roman *Venezianisches Finale*.
Ein international bekannter Dirigent wird in der Opernpause tot aufgefunden.
In seiner Garderobe riecht es unverkennbar nach Bittermandel - Zyankali.
Die Ermittlungen werden zu einem heiklen Fall für Commissario Brunetti.

[role="mt-4"]
=== Guido Blankenhorn

_Guido Blankenhorn_ ist ein ehemaliger Kriminalkommissar in Hamburg, der
vorzeitig in Pension geschickt wurde, nachdem er *ressortfremd* das Vorgehen
von Kollegen in einer linken Buchhandlung untersucht hatte.

Er wurde in den 1970er Jahren von _Uwe Friesel_ für eine Reihe von Hörspielen
des Norddeutscher Rundfunks geschaffen. Die Rolle des _Guido Blankenhorn_
wird in den Hörspielen von dem Schauspieler _Rolf Becker_ gesprochen.


[role="mt-5"]
== Die Hörspiele

In Playern finden Sie eine Auswahl der Folgen aus der Serie *Auf der Spur*.
Alle Episoden der Serie finden Sie unter
link://ardaudiothek.de/sendung/auf-der-spur-die-ard-ermittlerkrimis/94582432/[Die ARD Ermittlerkrimis, {browser-window--new}].

[role="mt-4 mb-4"]
[NOTE]
====
Über die Bedienelemente des Players können einzelne Folgen ausgewählt werden.
*Innerhalb* einer Folge kann sekundenweise vor- und zurückgesprungen werden,
falls man einen bestimmten Abschnitt nocheinmal hören oder überspringen möchte.

Aus Gründen des Urheberschutzes, werden alle Folgen direkt über das Angebot
der _ARD Audiohek_ geladen. Daher ist eine Internetverbindung zum Hören des
Podcasts *zwingend* erforderlich.
====


[role="mt-4"]
=== Detektivinnen

[role="mb-4"]
lorem:sentences[5]

[role="mb-5"]
.Auf der Spur · Detektivinnen
amplitude::auf_der_spur_detektivinnen_large[role="mb-5"]


[role="mt-4"]
=== Detektive

[role="mb-4"]
lorem:sentences[5]

[role="mt-4"]
==== Commissario Brunetti

Finden Sie im Player vier spannenden Fälles des _Commissario Brunetti_
von _Donna Leon_. Mit Michael König, Hille Darjes u.a.

[role="mb-4"]
* Sprecherin:   Hannelore Hoger
* Regie:        Hans Gerd Krogmann

[role="mb-5"]
.Auf der Spur · Commissario Brunetti
amplitude::auf_der_spur_brunetti_large[role="mb-5"]

[role="mt-4"]
==== Weitere Detektive

[role="mb-4"]
lorem:sentences[5]

[role="mb-5"]
.Auf der Spur · Detektive
amplitude::auf_der_spur_detektive_large[role="mb-8"]
