---
title:                                  Das Paradies der Damen
tagline:                                Roman von Emile Zolas

date:                                   2025-01-18
#last_modified:                         2025-01-18

description: >
                                        Ein Klassiker der Weltliteratur: "Das Paradies der Damen".
                                        Emile Zolas Roman entführt in ein Pariser Modewarenhaus,
                                        in die Salons der reichen Kundschaft und in die Kammern
                                        der kleinen Angestellten. Der Roman spielt im Paris
                                        des 19. Jahrhunderts und handelt von den Auswirkungen des
                                        Aufstiegs großer Kaufhäuser auf kleine Einzelhändler wie
                                        dem sozialen Gefüge der Gesellschaft seiner Zeit.

keywords: >
                                        WDR 5, Emile Zolas, Das Paradies der Damen,
                                        Roman, Hörbuch

categories:                             [ Audio ]
tags:                                   [ Hörbuch, Das Paradies der Damen ]

image:
  path:                                 //www1.wdr.de/radio/wdr5/sendungen/lies-mir-was-vor/kaufhaus-vintage-100~_v-gseapremiumxl.jpg
  width:                                1920
  height:                               1200

tts:                                    true
fab_menu_id:                            open_toc                                # default
personalization:                        false
comments:                               false

regenerate:                             false
permalink:                              /pages/public/audio/radioplay/paradies_der_damen/

resources:                              [ amplitudejs ]
resource_options:
  - attic:
      opacity:                          .8
      padding_top:                      550
      slides:
        - url:                          //www1.wdr.de/radio/wdr5/sendungen/lies-mir-was-vor/kaufhaus-vintage-100~_v-gseapremiumxl.jpg
          alt:                          Das Paradies der Damen
          badge:
            type:                       unsplash
            author:                     WDR 5
            href:                       //ardaudiothek.de/sendung/wdr-5-das-paradies-der-damen-hoerbuch/10378063/
---

// Page Initializer
// =============================================================================
// Enable the Liquid Preprocessor
:page-liquid:

// Set (local) page attributes here
// -----------------------------------------------------------------------------
// :page--attr:                         <attr-value>
:time-num--string:                      60+
:time-de--string:                       Minuten
:time-de--description:                  Audiozeit

//  Load Liquid procedures
// -----------------------------------------------------------------------------
{% capture load_attributes %}themes/{{site.template.name}}/procedures/global/attributes_loader.proc{%endcapture%}

// Load page attributes
// -----------------------------------------------------------------------------
{% include {{load_attributes}} scope="global" %}

// Page content
// ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
[role="dropcap"]
Ein Klassiker der Weltliteratur: "Das Paradies der Damen". Emile Zolas Roman
entführt in ein Pariser Modewarenhaus, in die Salons der reichen Kundschaft
und in die Kammern der kleinen Angestellten. Der Roman spielt im Paris des
19. Jahrhunderts und handelt von den Auswirkungen des Aufstiegs großer
Kaufhäuser auf kleine Einzelhändler wie dem sozialen Gefüge der Gesellschaft
seiner Zeit.

[subs=attributes]
++++
<div class="video-title">
  <i class="mdi mdi-gray mdi-clock-time-five-outline mdi-24px mr-2"></i>
  {time-num--string} {time-de--string} {time-de--description}
</div>
++++

// Include sub-documents (if any)
// -----------------------------------------------------------------------------
[role="mt-5"]
== Über den Autor

_Émile Zola_ war ein französischer Schriftsteller und Journalist, 1840 in
Paris geboren und verstarb dort 1902. Bevor er sich ganz der Literatur widmete,
arbeitete er als *Journalist* und *Kunstkritiker*. In dieser Zeit setzte er
sich für die Impressionisten ein, insbesondere für den Maler _Édouard Manet_.

Zola gilt als einer der bedeutendsten französischen Schriftsteller des
19. Jahrhunderts und wird als der Hauptvertreter des *Naturalismus* und
des *Realismus* in der Literatur gesehen.

Seine Werke zeichnen sich durch eine *detaillierte Darstellung* des sozialen
Lebens, der menschlichen Leidenschaften und der Auswirkungen von Umwelt und
Vererbung auf den Charakter aus.


[role="mt-5"]
== Über den Roman

Zolas Roman _Das Paradies der Damen_, Original: _Le Bonheur des Dames_,
erschien 1882 und bietet einen faszinierenden Einblick in das Paris des
späten 19. Jahrhunderts. Genauer gesagt in die Zeit der aufstrebenden
*Kaufhauskultur*. Zola zeichnet ein detailreiches Bild der sozialen und
wirtschaftlichen Veränderungen, die mit dem Aufstieg großer Warenhäuser
einhergingen.

Im Roman wird der Inhaber des Kaufhauses _Octave Mouret_ und dessen Leben in
der feinen Pariser Gesellschaft sowie seine Geschäftspraktiken thematisiert.
Vorbilder für diese Romanfigur waren der Unternehmer _Auguste Hériot_, der
das Pariser Kaufhaus _Grands Magasins du Louvre_ gründete, sowie _Aristide Boucicaut_,
der Gründer des _Le Bon Marché_.

Weiter wird die Geschichte von _Denise Baudu_ erzählt, einer jungen Frau aus
der Provinz, die nach den Tode der Eltern mit ihren kleineren Brüdern
_Pépé_ und _Jean_ nach Paris zieht um Arbeit zu finden. Zunächst sucht sie
ihren Onkel auf, der als *Tuchwarenhändler* in der Stadt lebt. Doch der Onkel
ist als Einzelhändler in Konkurrenz zum *Paradies der Damen* unter hohen
wirtschaftlichen Druck geraten, und kann Denise keine Stellung anbieten.

Sie findet eine Anstellung im großen Kaufhaus *Paradies der Damen*, das immer
mächtiger wird und die kleinen Geschäfte in der Umgebung in den Ruin treibt.
_Denise_ steigt in der Hierarchie des Kaufhauses auf und wird Zeugin der
harten Arbeitsbedingungen der Verkäuferinnen, der Konkurrenz unter den
Angestellten und der skrupellosen Geschäftspraktiken des Besitzers
Octave Mouret. Mouret ist ein charismatischer und ehrgeiziger Mann, der
sein Kaufhaus zu einem wahren Imperium ausbaut.

Die Liebe von _Denise_ zu _Octave Moure_ verkompliziert ihr Handeln, da _Denise_
zwischen ihren eigenen Ambitionen und ihrer Zuneigung zu ihm hin- und
hergerissen ist.

*Das Paradies der Damen* ist mehr als nur ein Roman über ein Kaufhaus. Zola
liefert eine sozialkritische Analyse der modernen Gesellschaft und ihrer
Widersprüche. Sein Werk gilt als eines der bedeutendsten Werke des Naturalismus
und hat die Literatur und das gesellschaftliche Denken nachhaltig beeinflusst.


[role="mt-5"]
=== Charaktere des Romans

Der Roman ist komplex und eine ganze Reihe von Personen spielen hier eine
Rolle. Da nicht jeder ein Gedächtniskünstler was Name und Personen betrifft,
hier die wichtigsten Charaktere des Romans.

[cols="4,8a", subs=+macros, options="header", width="100%", role="rtable mt-4 mb-4"]
|===
|Figur |Beschreibung

|_Denise Baudu_
|Eine junge Provinzlerin, die nach Paris kommt, um Arbeit zu finden. Sie ist
die Hauptprotagonistin des Romans.
                        
|_Genevieve Baudu_
|Kusine von Denise. Für Genevieve ist seit 10 Jahren eine Heirat mit
Colomban geplant, wird aber aus wirtschaftlichen Gründen des Vaters
(Tuchwarenhändler) immer wieder verschoben.

|_Pépé_ \| _Jean Baudu_
|Denises jüngere Brüder.

|_Familie Baudu_
|Denises Eltern und Geschwister. Sie leben in der Provinz und sind besorgt
um Denises Wohlergehen. Onkel Baudu in Paris ist Tuchwarenhändler der als
Einzelhändler in Konkurrenz zu "Paradies der Damen" unter hohen
wirtschaftlichen Druck gerät.

|_Familie Robineau_
|Famile des Schirmhändlers und bekannt mit der Familie Baudu, dem
Tuchwarenhändler. Das Haus und der gemietete Laden von Robineau grenzt
an das *Paradies der Damen* und soll für Erweiterungen des Kaufhauses
aufgekauft werden. Robineau wehrt sich nack Kräften in einem erbittertem
Kampf gegen die Übernahme, obwohl die finanziellen Angebote zur Aufgabe
des laufenden Mietvertrags von noch 10 Jahren aufzugeben enorm hoch
sind.

|_Pauline_
|Denises enge Freundin und Kollegin. Pauline ist eine gutmütige junge Frau.

|_Deloche_
|_Denise Baudu_ trifft _Deloche_ am ersten Tag der Vorstellung als Mitarbeiter
im *Paradies der Damen*. Er wird als Verkäufer in der Konfektionsabteilung
angenommen. Im Laufe der Zeit ist Deloche unglückich verliebt in _Denise Baudu_,
die ihm jedoch ihre Kameradschaft versichert.

|_Favier_
|Verkäufer in der Konfektionsabteilung des *Paradies der Damen*.

|_Hutin_
|Zweiter Verkäufer der Konfektionsabteilung des *Paradies der Damen*.

|_Claire Prunaire_
|Verkäuferin im *Paradies der Damen*, die um die Aufmerksamkeit von
_Octave Mouret_ buhlt und in Konkurrenz zu _Frau Desforges_ eine der
Geliebten von Mouret wird. _Colomban_ liebt _Claire_, jedoch chancenlos.
Oobwohl er gleichzeitig seit Jahren eine Heirat mit _Genevieve Baudu _
geplant ist.

|_Octave Mouret_
|*Besitzer* des Kaufhauses *Das Paradies der Damen*. Er ist ein skrupelloser
Geschäftsmann, der keine Skrupel hat, um seine Ziele zu erreichen. _Mouret_
ist ein Frauenheld und hat eine komplexe Beziehung zu _Denise_.

|_Inspektor Jouve_
|(Haus-)Detektiv im *Paradies der Damen*.

|_Baron von Hartmann_
|Immobilienbanker, der die Liegenschaften in der Straße des *Das Paradies der Damen*
aufkauft.

|_Bouthemont_
|Mitarbeiter und *Teilhaber* am Kaufhaus *Das Paradies der Damen*.

|_Henriette Desforges_
|*Witwe eines Börsenspekulanten* und heimliche *Geliebte* von _Octave Mouret_.

|_Madame Aurélie_
|Leiterin der Damenabteilung. _Madame Aurélie_ ist eine strenge und unnahbare
Frau. Sie verschafft ihrem Sohn die Stellung des Hauptkassierers von Kasse 10.

|_Bourdoncle_
|*Stellvertreter* von _Octave Mouret_.

|_Colomban_
|*Chef der Etage*. _Colomban_ ist ein korpulenter, jovialer junger Mann.
Eine Heirat mit _Genevieve Baudu_ ist geplant.

|_Frau von Boves_
|*Prominente Kundin* des Kaufhauses *Paradies der Damen*.

|_Madame de Bovary_
|*Prominente Kundin* des Kaufhauses *Paradies der Damen*. Sie ist eine elegante
und reiche Frau, die unglücklich in ihrer Ehe ist und im Kaufhaus Ablenkung
sucht.

|_Marguerite_
|Haushälterin von _Octave Mouret_. _Marguerite_ ist eine treue und loyale
Dienerin.

|_Theodore_
|*Sohn* von _Octave Mouret_ und seiner *ersten Frau*. _Theodore_ ist ein
kränkliches und sensibles Kind.

|_Jean de Joigny_
|Junger Mann, der sich in _Denise_ verliebt. _Jean_ ist ein idealistischer
und unkonventioneller Künstler. Er steht in Konkurrenz zu _Octave Mouret_.

|_Paul von Vallagnosc_
|*Jugendfreund* von _Octave Mouret_.

|_Bourras_
|*Alter Verkäufer* im Kaufhaus, der die Veränderungen im Einzelhandel kritisch
betrachtet und nostalgisch nach den alten Tagen des Kleinhändlers ist.

|===


[role="mt-5"]
== Player

Im Player finden Sie alle Folgen des Hörspiels. Es werden alle Episoden
automatisch nacheinander abgespielt. Über die Bedienelemente des Players können
einzelne Folgen ausgewählt werden. *Innerhalb* einer Folge kann vor- und
zurückgesprungen werden, falls man einen bestimmten Abschnitt nocheinmal hören
oder überspringen möchte.

[role="mt-4 mb-5"]
[NOTE]
====
Aus Gründen des Urheberschutzes, lädt der Audio Player alle Folgen direkt
über das Angebot der link:https://www.ardaudiothek.de/[ARD Audiothek, {browser-window--new}].
Daher ist eine Internetverbindung zum Hören *zwingend* erforderlich.
====

[role="mt-5 mb-5"]
.Das Paradies der Damen · Gelesen von Regina Münch
amplitude::paradies_der_damen_large[role="mb-8"]


