---
title:                                  Ephraim Kishon
title_extention:                        Satire
tagline:                                Satire

date:                                   2025-02-11
#last_modified:                         2025-02-11

description: >
                                        Ephraim Kishon war ein israelischer Schriftsteller, Satiriker,
                                        Journalist, Drehbuchautor und Filmregisseur ungarischer Herkunft.
                                        Er gilt als einer der meistgelesenen und erfolgreichsten Satiriker
                                        des 20. Jahrhunderts im deutschsprachigen Raum.
keywords: >
                                        Hörspiel, Radioplay, Ephraim Kishon

categories:                             [ Audio ]
tags:                                   [ Hörspiel, Ephraim Kishon ]

image:
  path:                                 //media1.faz.net/ppmedia/w1240/aktuell/3527659893/1.9935169/16x9/ephraim-kishon-im-jahr-1992.jpg
  width:                                1920
  height:                               1280


regenerate:                             false
personalization:                        true
permalink:                              /pages/public/audio/radioplay/ephraim-kishon/

resources:                              [ amplitudejs ]
resource_options:  
  - attic:
      opacity:                          .8
      padding_top:                      550
      slides:
        - url:                          //media1.faz.net/ppmedia/w1240/aktuell/3527659893/1.9935169/16x9/ephraim-kishon-im-jahr-1992.jpg
          alt:                          Ephraim Kishon
          badge:
            type:                       unsplash
            author:                     FAZ
            href:                       //www.faz.net/aktuell/feuilleton/buecher/autoren/ephraim-kishon-zum-100-geburtstag-biographie-ein-leben-fuer-den-humor-19933530.html
---

// Page Initializer
// =============================================================================
// Enable the Liquid Preprocessor
:page-liquid:

// Set (local) page attributes here
// -----------------------------------------------------------------------------
// :page--attr:                         <attr-value>

//  Load Liquid procedures
// -----------------------------------------------------------------------------
{% capture load_attributes %}themes/{{site.template.name}}/procedures/global/attributes_loader.proc{%endcapture%}

// Load page attributes
// -----------------------------------------------------------------------------
{% include {{load_attributes}} scope="global" %}


// Page content
// ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
[role="dropcap"]
Ephraim Kishon (1924-2005) war ein israelischer Schriftsteller, Satiriker,
Journalist, Drehbuchautor und Filmregisseur ungarischer Herkunft. Er gilt als
einer der meistgelesenen und erfolgreichsten Satiriker des 20. Jahrhunderts
im deutschsprachigen Raum.

++++
<div class="video-title">
  <i class="mdib mdi-bs-primary mdib-clock mdib-24px mr-2"></i>
  10+ Minuten Audiozeit
</div>
++++

// Include sub-documents (if any)
// -----------------------------------------------------------------------------
[role="mt-5"]
== Über Ephraim Kishon

Kishon war ein scharfer Beobachter des menschlichen Verhaltens und der
gesellschaftlichen Verhältnisse. Seine Satiren zeichnen sich durch ihren
feinen Humor, ihre Ironie und ihren bissigen Witz aus.

// .Ephraim Kishon · Zeitzeugen 
// youtube::6NfppAgDCqk[poster="/assets/video/poster/youtube/zeitzeugen/zeitzeugen.jpg" role="mt-4 mb-4"]

Die Geschichten Kishons spiegeln die Zeit wider, in der Ephraim Kishon lebte
und schrieb, hauptsächlich die zweite Hälfte des 20. Jahrhunderts. Die
satirischen Kurzgeschichten sind zeitlos und sprechen Leser jeden Alters
an.

Kishon war ein Meister der Sprachkunst und verstand es, durchaus komplexe
Themen auf sehr unterhaltsame Weise darzustellen.

[role="mt-5"]
== Beste Geschichten

Die besten *Geschichten* von Ephraim Kishon sind eine Sammlung humorvoller,
satirischer Kurzgeschichten. Kishon betrachtet mit viel Ironie und Witz die
kleinen und großen Probleme des Alltags in Israel der 1970er Jahre.

[role="mt-4"]
=== Beste Familiengeschichten

Die *Familiengeschichten* behandeln alltägliche Situationen. Typische
Erlebnisse wie Einkaufen, Urlaub, Schulausflüge, Erziehungsprobleme und den
alltäglichen Wahnsinn des Familienlebens. Im Mittelpunkt stehen Kishon selbst,
seine *beste Ehefrau von allen* und seine drei Kinder. Kishon nimmt in den
Familiengeschichten sich und seine Familie dabei liebevoll auf die Schippe.

.Ephraim Kishon · Beste Familiengeschichten
amplitude::ephraim_kishon_beste_familiengeschichten_yt_large[role="mb-5"]

[role="mt-4"]
=== Beste Autofahrergeschichten

Diw *Autofahrergeschichten* sind eine Sammlung humorvoller Satiren rund um das
Thema Autofahren. Sie schildern auf unterhaltsame Weise die Absurditäten und
Tücken des modernen Straßenverkehrs. Beispielsweise Familienausflüge. Warum
eine Autofahrt mit der Familie spannender sein kann als jeder Krimi.
Oder wie eine Parkplatzsuche zu einer unvergesslichen *Safari* wird. Ebenso
technische Pannen: Wie eine angezogene Handbremse zum *drahtlosen Telefon*
mutiert. Und Verkehrskontrollen: Wie man sich auf humorvolle Art und Weise
an Verkehrspolizisten *rächen* kann.

.Ephraim Kishon · Beste Autofahrergeschichten
amplitude::ephraim_kishon_beste_autofahrer_geschichten_yt_large[role="mb-8"]
