---
title:                                  Mimi Rutherfurt
title_extention:                        Geheimnisvolle Kriminalfälle 
tagline:                                Geheimnisvolle Kriminalfälle 

date:                                   2024-09-21
#last_modified:                         2024-01-01

description: >
                                        Mimi Rutherfurt, eine englische Lady, möchte in der britischen Provinz
                                        eigentlich einen ruhigen Lebensabend verbringen. Doch immer wieder schlittert
                                        sie in Kriminalfälle. Die Geschichten sind angelehnt an die legendären
                                        Kriminalgeschichten von "Miss Marple" der Bestseller Autorin "Agatha Christie".
keywords: >
                                        Hörspiel, Radioplay, Mimi Rutherfurt

categories:                             [ Audio ]
tags:                                   [ Hörspiel, Mimi Rutherfurt ]

image:
  path:                                 /assets/image/leute/margaret-rutherford.jpg
  width:                                1920
  height:                               1280

attic:                                  false
regenerate:                             false
personalization:                        true
permalink:                              /pages/public/audio/radioplay/mimi-rutherfurt/

resources:                              [ amplitudejs ]
resource_options:  
  - attic:
      opacity:                          .8
      padding_top:                      550
      slides:
        - url:                          //bilder.deutschlandfunk.de/FI/LE/_5/02/FILE_50248b104e9d636ac7cd115f87e007b2/7062174-169-jpg-100-1920x1080.jpg
          alt:                          Margaret Rutherford
          badge:
            type:                       unsplash
            author:                     Deutschlandfunk
            href:                       //www.deutschlandfunk.de/125-geburtstag-von-margaret-rutherford-fuer-immer-miss-100.html       
---

// Page Initializer
// =============================================================================
// Enable the Liquid Preprocessor
:page-liquid:

// Set (local) page attributes here
// -----------------------------------------------------------------------------
// :page--attr:                         <attr-value>

//  Load Liquid procedures
// -----------------------------------------------------------------------------
{% capture load_attributes %}themes/{{site.template.name}}/procedures/global/attributes_loader.proc{%endcapture%}

// Load page attributes
// -----------------------------------------------------------------------------
{% include {{load_attributes}} scope="global" %}


// Page content
// ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
[role="dropcap"]
Mimi Rutherfurt, eine englische Lady, möchte in der britischen Provinz
eigentlich einen ruhigen Lebensabend verbringen. Doch immer wieder schlittert
sie in Kriminalfälle. Die Geschichten sind angelehnt an die legendären
Kriminalgeschichten von "Miss Marple" der Bestseller Autorin "Agatha Christie".

++++
<div class="video-title">
  <i class="mdib mdi-bs-primary mdib-clock mdib-24px mr-2"></i>
  45+ Minuten Audiozeit
</div>
++++

// Include sub-documents (if any)
// -----------------------------------------------------------------------------
[role="mt-5"]
== Über die Hörspiele
// https://www.youtube.com/@MaritimVerlag
// https://music.apple.com/de/album/margaret-rutherford-collectors-edition-1/1694329605

Die Hörspiel-Serie *Mimi Rutherfurt* des
https://maritim-hoerspiele.de[Maritim Verlags, {browser-window--new}]
ist eine wundervolle Hommage an die beliebten *Miss Marple* Romane von
Agatha Christie.

Unter den Sprecherinnen und Sprechern sind viele alte Bekannte. Die Hauptfigur
Lady Rutherfurt wird von _Gisela Fritsch_ verkörpert; sie verstarb in Jahr 2013.
Seit Folge 37 spricht _Ingrid Stein_ die Stimme von Mimi Rutherfurt.

[role="mt-4 mb-4"]
[NOTE]
====
Aus Gründen des Urheberschutzes, lädt der Audio Player alle Folgen direkt über
das Angebot der Plattform link:https://youtube.com/[YouTube, {browser-window--new}].
Eine Internetverbindung ist zum Hören daher *zwingend* erforderlich.
====


[role="mt-5"]
== Episoden

Die alte Dame erlebt ihre Abenteuer nicht nur im provinziellen Idyll. Unter
anderem bringt sie das Verbrechen in den Buckingham Palace, auf den Luxusliner
Queen Mary und nach Stonehenge.

.Mimi Rutherfurt · Maritim Verlag
amplitude::mimi_rutherfurt_yt_large[role="mb-8"]
