---
title:                                  Mimi Rutherfurt
title_extention:                        YT Video Integration
tagline:                                YT Video Integration

date:                                   2024-09-21
#last_modified:                         2024-01-01

description: >
                                        Die englische Lady "Mimi Rutherfurt" möchte in der britischen
                                        Provinz eigentlich einen ruhigen Lebensabend verbringen. Doch
                                        immer wieder schlittert sie in geheimnisvolle Kriminalfälle.
                                        Die Fälle sind angelehnt an die Romane der legendären
                                        Miss Marple Reihe von Agatha Christie.
keywords: >
                                        Hörspiel, Radioplay, Mimi Rutherfurt

categories:                             [ Audio ]
tags:                                   [ Hörspiel, Mimi Rutherfurt ]

image:
  path:                                 /assets/image/leute/margaret-rutherford.jpg
  width:                                1920
  height:                               1280

attic:                                  false
regenerate:                             false
personalization:                        true
permalink:                              /pages/public/audio/radioplay/mimi-rutherfurt/

resources:                              [ amplitudejs ]
resource_options:
  - attic:
      slides:
        - url:                          /assets/image/leute/margaret-rutherford.jpg
          alt:                          Video Tester
---

// Page Initializer
// =============================================================================
// Enable the Liquid Preprocessor
:page-liquid:

// Attribute settings for section control
//
:ytp-api--description:                  false
:ytp--example:                          false
:ytp--audio-player:                     true
:ms-slider-video--example:              false

:manon-melodie--playlist:               //youtube.com/channel/UCEsIlUzfXYT5AZSOVnbFqsQ

// Set (local) page attributes here
// -----------------------------------------------------------------------------
// :page--attr:                         <attr-value>

//  Load Liquid procedures
// -----------------------------------------------------------------------------
{% capture load_attributes %}themes/{{site.template.name}}/procedures/global/attributes_loader.proc{%endcapture%}

// Load page attributes
// -----------------------------------------------------------------------------
{% include {{load_attributes}} scope="global" %}


// Page content
// ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
[role="dropcap"]
Mimi Rutherfurt, eine englische Lady, möchte in der britischen Provinz
eigentlich einen ruhigen Lebensabend verbringen. Doch immer wieder schlittert
sie in geheimnisvolle Kriminalfälle hinein.

Die Geschichten sind angelehnt an die Fälle der legendären _Miss Marple_-Reihe
von _Agatha Christie_.

++++
<div class="video-title">
  <i class="mdib mdi-bs-primary mdib-clock mdib-24px mr-2"></i>
  45+ Minuten Audiozeit
</div>
++++

// Include sub-documents (if any)
// -----------------------------------------------------------------------------
[role="mt-5"]
== Über die Hörspiele
// https://www.youtube.com/@MaritimVerlag
// https://music.apple.com/de/album/margaret-rutherford-collectors-edition-1/1694329605

Die Hörspiel-Serie *Mimi Rutherfurt* des
https://maritim-hoerspiele.de[Maritim Verlags, {browser-window--new}]
ist eine wundervolle Hommage an die beliebten *Miss Marple* Romane von
Agatha Christie.

Unter den Sprecherinnen und Sprechern sind viele alte Bekannte. Die Hauptfigur
Lady Rutherfurt wird von _Gisela Fritsch_ verkörpert; sie verstarb in Jahr 2013.
Seit Folge 37 spricht _Ingrid Stein_ die Stimme von Mimi Rutherfurt.

[role="mt-4 mb-4"]
[TIP]
====
Aus Gründen des Urheberschutzes, werden alle Folgen direkt über das Angebot
der Plattform
https://www.youtube.com/watch?v=qEhzpBJpUq0&list=PLLsYXB2u7E7CjL97CTVUnJl4WY3ws6Ptj[YouTube, {browser-window--new}]
(Playlist) geladen. Eine Internetverbindung zum Hören der Hörspiele ist daher
*zwingend* erforderlich.
====

[role="mt-5"]
== Episoden

Die alte Dame erlebt ihre Abenteuer nicht nur im provinziellen Idyll. Unter
anderem bringt sie das Verbrechen in den Buckingham Palace, auf den Luxusliner
Queen Mary und nach Stonehenge.

.Mimi Rutherfurt · Maritim Verlag
amplitude::mimi_rutherfurt_yt_large[role="mt-4 mb-8"]


