---
title:                                  Manon Mélodie
tagline:                                Jazzmusikerin
title_extention:                        Jazzmusikerin der Gegenwart


date:                                   2025-02-08
#last_modified:                         2025-02-08

description: >
                                        Die kanadische Jazzpianistin und Sängerin Diana Krall
                                        ist eine der bekanntesten und erfolgreichsten Jazzmusikerinnen
                                        der Gegenwart. Sie ist Botschafterin des kanadischen Roten Kreuzes
                                        und unterstützt verschiedene Projekte für Kinder und Jugendliche.

keywords:                               Musik, Chanson, Manon Mélodie

categories:                             [ Video ]
tags:                                   [ Musik , Manon Mélodie ]

image:
  path:                                 //kj.de/images/media/6078_20579.jpg
  width:                                1280
  height:                               720

compress:                               false
fab_menu_id:                            open_toc
comments:                               false
regenerate:                             false
permalink:                              /pages/public/video/music/manon_melodie/

resources:                              [ amplitudejs ]
resource_options:
  - attic:
      padding_top:                      550
      slides:
        - url:                          //img.youtube.com/vi/fFn1GZIYC4Y/maxresdefault.jpg
          alt:                          Manon Mélodie
---

// Page Initializer
// =============================================================================
// Enable the Liquid Preprocessor
:page-liquid:

// Set (local) page attributes here
// -----------------------------------------------------------------------------
// :page--attr:                         <attr-value>
:show-audio:                            true

//  Load Liquid procedures
// -----------------------------------------------------------------------------
{% capture load_attributes %}themes/{{site.template.name}}/procedures/global/attributes_loader.proc{%endcapture%}

// Load page attributes
// -----------------------------------------------------------------------------
{% include {{load_attributes}} scope="global" %}


// Page content
// ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
[role="dropcap"]
Die kanadische Jazzpianistin und Sängerin Diana Krall ist eine der bekanntesten
und erfolgreichsten Jazzmusikerinnen der Gegenwart. 

++++
<div class="video-title">
  <i class="mdib mdi-bs-primary mdib-clock mdib-24px mr-2"></i>
  3+ Minuten Audiozeit
</div>
++++

// Include sub-documents (if any)
// -----------------------------------------------------------------------------
// [role="mt-5"]
// == Über Diana Krall
// // See: https://de.wikipedia.org/wiki/Diana_Krall

// Diana Krall wuchs in einer musikalischen Familie auf. Ihre Mutter war Sängerin,
// ihr Vater spielte Klavier. Schon als Kind erhielt sie Klavierunterricht und
// sang in verschiedenen Chören. Sie studierte am Berklee College of Music in
// Boston und zog später nach Los Angeles, wo sie mit dem Musiker Jimmy Rowles
// zusammenarbeitete.

// 1990 ging Diana Krall nach New York und spielte in verschiedenen Bars und Clubs.
// Ihr Debütalbum *Stepping Out* veröffentlichte sie 1993. Der Durchbruch gelang
// ihr mit dem Album *Come On Over* im Jahr 1999. Heute ist Diana Krall eine der
// meistverkauften Jazzkünstlerinnen aller Zeiten. Sie hat mehrere Grammys
// gewonnen und mit vielen bekannten Musikern zusammengearbeitet, darunter
// _Tony Bennett_, _Paul McCartney_ und _Barbra Streisand_.


ifeval::[{show-audio} == true]
[role="mt-5"]
== Audio

Die Playlist von Diana Krall auf YouTobe steht auch als Audio-Version zur
Verfügung.

[role="mt-4 mb-5"]
[NOTE]
====
Aus Gründen des Urheberschutzes, lädt der Audio Player alle Stücke der
*Playlist* direkt über das Angebot der YouTube Plattform
link:https://www.youtube.com/watch?v=7sxK8ghb9PU&list=PL63F10BA7870008CB[Diana Krall (Playlist), {browser-window--new}].

Eine Internetverbindung ist zum Hören daher *zwingend* erforderlich.
====

.Manon Mélodie · YouTube
amplitude::manon_melodie_yt[role="mt-4 mb-8"]

endif::[]


