---
title:                                  SpontanOrama
tagline:                                Talk mit Ralf Schmitz und Gästen

date:                                   2024-09-11
last_modified:                          2024-12-28

description: >
                                        Spontanorama, der Alles-Ist-Möglich Talk. In den Gesprächen mit
                                        seinen zufälligen Gästen ist alles möglich, denn kein Gast ist
                                        vorherbestimmt. Ralf Schmitz weiß nie, wer als Nächstes durch die
                                        Tür des Studios kommt. Während Ralf ungeduldig wartet, läuft draußen
                                        ein Mitglied seines Teams durch die Straßen der Kölner Innenstadt.
                                        Immer auf der Suche nach Passantinnen und Passanten, die in diesem
                                        Moment bereit sind, alles stehen und liegen zu lassen um spontan mit
                                        Ralf zu  quatschen.
keywords: >
                                        Podcast, Spontanorama, Ralf Schmitz

categories:                             [ Audio ]
tags:                                   [ Podcast, Ralf Schmitz ]

image:
  path:                                 /assets/image/leute/ralf-schmitz.jpg
  width:                                1280
  height:                               720

tts:                                    true
fab_menu_id:                            open_toc                                # default
personalization:                        false
comments:                               false

regenerate:                             false
permalink:                              /pages/public/audio/podcast/spontanorama/

resources:                              [ amplitudejs ]
resource_options:
  - attic:
#     opacity:                          0.5
      padding_top:                      550
      slides:
        - url:                          /assets/image/leute/ralf-schmitz.jpg
          alt:                          Ralf Schmitz
---

// Page Initializer
// =============================================================================
// Enable the Liquid Preprocessor
:page-liquid:

// Set (local) page attributes here
// -----------------------------------------------------------------------------
// :page--attr:                         <attr-value>

//  Load Liquid procedures
// -----------------------------------------------------------------------------
{% capture load_attributes %}themes/{{site.template.name}}/procedures/global/attributes_loader.proc{%endcapture%}

// Load page attributes
// -----------------------------------------------------------------------------
{% include {{load_attributes}} scope="global" %}


// Page content
// ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
[role="dropcap"]
Spontanorama, der Alles-Ist-Möglich Talk. Kein Gast in den Gesprächen ist
vorherbestimmt. Ralf weiß nie, wer als Nächstes durch die Tür des Studios
kommt. Die Podcasts sind im wahrsten Sinne des Wortes eines: Spontan.
Und immer: Überraschend (gut).

++++
<div class="video-title">
  <i class="mdib mdi-bs-primary mdib-clock mdib-24px mr-2"></i>
  60+ Minuten Audiozeit
</div>
++++

// Include sub-documents (if any)
// -----------------------------------------------------------------------------
[role="mt-5"]
== Über Ralf Schmitz

Ralf Schmitz ist ein vielseitiger deutscher Unterhaltungskünstler. Viele
Menschen in Deutschland werden ihn kennen, aber nicht unbedingt alle.
Das wäre aber schade, da er durch viele Talente überzeuen kann. Seine
Schlagfertigkeit, das improvisatorische Können und seine energiegeladenen
Auftritte machen ihn einzigartig.

Er begann seine Karriere im Improvisationstheater _Die Springmaus_ in Bonn.
Der Durchbruch gelang mit der Sketch-Comedy-Show _Die Dreisten Drei_, für
die er im Jahr 2003 als *Newcomer des Jahres* den Deutschen Comedypreis
bekam.

Als Moderaator hat Ralf zahlreiche TV-Shows präsentert. Darunter _Take Me Out_
und _Schmitz in the City_. Als Schauspieler hat er in Filmen und Serien 
mitgewirkt, die schon heute legendär sind. Darunter die TV-Show _Schillerstraße_
und der Kino-Film _7 Zwerge – Männer allein im Wald_ von 2004; eine Komödie
von und mit Otto Waalkes.

[role="mt-4"]
=== Mehr über Ralf

Ralf Schmitz ist einer der beliebtesten deutschen Comedians. Bekannt für
seine Schnelligkeit und dem Talent zur Improvisation. Mehr zu Ralf unter:

* https://de.wikipedia.org/wiki/Ralf_Schmitz[Wikipedia, {browser-window--new}]
* https://www.prosieben.de/themen/stars/profile/ralf-schmitz-64334[ProSieben, {browser-window--new}]

Als Solokünstler begeistert er mit eigenen Bühnenprogrammen, die in vielen
deutschen Städten zu sehen sind. Brüllend komische Stand-up-Nummern,
Impro-Comedy mit dem Publikum wechseln in Höchstgeschwingkeit mit unglaublichen
Geschichten und Anekdoten. Aktuelle Termine und Tickets zum Bühnenprogramm kann
man hier finden: https://www.eventim.de/artist/ralf-schmitz[Eventim - Ralf Schmitz, {browser-window--new}].

Mit seinem neuesten Projekt, dem Podcast-Format *SpantanOrama* aus dem Jahr 2024,
stellt Ralf eimal mehr sein Können als Moderator und sein Interesse an Menschen
wie deren Geschichten unter Beweis.

Mehr zu den Episoden des Podcast in den folgenden Abschnitten.


[role="mt-5"]
== Über den Podcast

Während  Ralf Schmitz im Studio ungeduldig wartet, läuft draußen ein Mitglied
seines Teams durch die Straßen der Kölner Innenstadt. Immer auf der Suche nach
zufälligen Passantinnen und Passanten, die spontan bereit sind alles stehen
und liegen zu lassen um mit Ralf für eine Stunde zu quatschen.

[role="mt-4 mb-4"]
[NOTE]
====
Aus Gründen des *Urheberschutzes*, lädt der Audio Player alle Folgen über
das Angebot der https://earlystudios.com/[Early Studios, {browser-window--new}],
die den Podcast produziert. Zum Hören der Episoden ist eine Internetverbindung
zwingend *erforderlich*.

Es erscheint jeweils an *Donnerstagen* in *jeder Woche* eine neue Folge.
====


[role="mt-5"]
== Episoden

Jede Folge ist eine Überraschung. Die Gespräche sind eine wilde Mischung aus
Wortwitz, einzigartigen persönlichen wie unerwarteten Geschichten von Ralf
und seiner Gäste.

[role="mt-4 mb-5"]
[TIP]
====
Die Episoden werden auf dieser Seite *wöchentlich* aktualisiert. Außerden sind
alle Folgen des Podcasts überall da zu finden, wo es Podcasts gibt. Zum
Beispiel bei:

* https://podcast.de/podcast/3446603/spontanorama[Podcasts.de, {browser-window--new}]
* https://podcasts.apple.com/de/podcast/spontanorama/id1741818812[Apple Podcasts, {browser-window--new}]
* https://open.spotify.com/show/1CZ31uaQ6JTwood52CKQ9H[Spotify, {browser-window--new}]
====

[role="mt-4"]
=== 2025

Im Player sind alle Episoden verfügbar, die im Jahr *2025* produziert
wurden.

.Spontanorama · 2025
amplitude::spontanorama_2025_large[role="mt-4 mb-5"]

[role="mt-4"]
=== 2024

In April startete der neue Podcast von Ralf Schmitz. Im Player sind alle
Episoden verfügbar, die im Jahr *2024* produziert wurden.

.Spontanorama · 2024
amplitude::spontanorama_2024_large[role="mt-4 mb-8"]

