---
title:                                  Spontanorama
tagline:                                Podcast mit Ralf Schmitz

date:                                   2024-09-11
#last_modified:                         2024-09-11

description: >
                                        Hier ist alles möglich, denn kein Gast ist vorherbestimmt – Ralf Schmitz weiß
                                        nie, wer als Nächstes durch die Tür tritt. Während er im Studio ungeduldig
                                        wartet, läuft draußen ein Teammitglied durch die Straßen der Kölner Innenstadt,
                                        auf der Suche nach Passantinnen und Passanten, die jetzt in diesem Moment
                                        bereit sind, alles stehen und liegen zu lassen, um spontan mit Ralf zu
                                        quatschen.
keywords: >
                                        Podcast, SpontanOrama, Ralf Schmitz

categories:                             [ Audio ]
tags:                                   [ Podcast, Ralf Schmitz ]

image:
  path:                                 /assets/image/leute/ralf-schmitz.jpg
  width:                                1280
  height:                               720

tts:                                    true
fab_menu_id:                            open_toc                                # default
personalization:                        false
comments:                               false

regenerate:                             false
permalink:                              /pages/public/audio/podcast/spontanorama/

resources:                              [ amplitudejs ]
resource_options:
  - attic:
#     opacity:                          0.5
      padding_top:                      550
      slides:
        - url:                          /assets/image/leute/ralf-schmitz.jpg
          alt:                          Ralf Schmitz
---

// Page Initializer
// =============================================================================
// Enable the Liquid Preprocessor
:page-liquid:

// Set (local) page attributes here
// -----------------------------------------------------------------------------
// :page--attr:                         <attr-value>

//  Load Liquid procedures
// -----------------------------------------------------------------------------
{% capture load_attributes %}themes/{{site.template.name}}/procedures/global/attributes_loader.proc{%endcapture%}

// Load page attributes
// -----------------------------------------------------------------------------
{% include {{load_attributes}} scope="global" %}


// Page content
// ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
[role="dropcap"]
Spontanorama, mit dem Format ist alles möglich, denn kein Gast ist
vorherbestimmt. Ralf Schmitz weiß nie, wer als Nächstes durch die Tür kommt.

++++
<div class="video-title">
  <i class="mdib mdi-bs-primary mdib-clock mdib-24px mr-2"></i>
  60+ Minuten Audiozeit
</div>
++++

// Include sub-documents (if any)
// -----------------------------------------------------------------------------
[role="mt-5"]
== Über den Podcast

Während Ralf im Studio ungeduldig wartet, läuft draußen ein Teammitglied
durch die Straßen der Kölner Innenstadt auf der Suche nach Passantinnen
und Passanten, die spontan bereit sind, alles stehen und liegen zu lassen,
um mit Ralf Schmitz für eine Stunde zu quatschen.

[role="mt-4 mb-4"]
[TIP]
====
Aus Gründen des Urheberschutzes, werden alle Folgen direkt über das Angebot
der _Spotify_ Podcast-Plattform
https://megaphone.spotify.com/de-DE[Megaphone, {browser-window--new}]
geladen. Eine Internetverbindung zum Hören des Podcasts ist *zwingend*
erforderlich.
====


[role="mt-5"]
== Episoden

Im Player sind alle Episoden verfügbar, die bis *September 2024* produziert
wurden. Es erscheint jeden Donnerstag eine neue Folge.

.Spontanorama 2024
amplitude::spontanorama_2024_large[role="mt-4 mb-7"]
