---
title:                                  Spontanorama
tagline:                                Podcast mit Ralf Schmitz

date:                                   2024-09-11
#last_modified:                         2024-09-11

description: >
                                        Hier ist alles möglich, denn kein Gast ist vorherbestimmt – Ralf Schmitz weiß
                                        nie, wer als Nächstes durch die Tür tritt. Während er im Studio ungeduldig
                                        wartet, läuft draußen ein Teammitglied durch die Straßen der Kölner Innenstadt,
                                        auf der Suche nach Passantinnen und Passanten, die jetzt in diesem Moment
                                        bereit sind, alles stehen und liegen zu lassen, um spontan mit Ralf zu
                                        quatschen.
keywords: >
                                        Podcast, SpontanOrama, Ralf Schmitz

categories:                             [ Audio ]
tags:                                   [ Podcast, Ralf Schmitz ]

image:
  path:                                 /assets/image/leute/ralf-schmitz.jpg
  width:                                1280
  height:                               720

tts:                                    true
fab_menu_id:                            open_toc                                # default
personalization:                        false
comments:                               false

regenerate:                             false
permalink:                              /pages/public/audio/podcast/spontanorama/

resources:                              [ amplitudejs ]
resource_options:
  - attic:
#     opacity:                          0.5
      padding_top:                      550
      slides:
        - url:                          /assets/image/leute/ralf-schmitz.jpg
          alt:                          Ralf Schmitz
---

// Page Initializer
// =============================================================================
// Enable the Liquid Preprocessor
:page-liquid:

// Set (local) page attributes here
// -----------------------------------------------------------------------------
// :page--attr:                         <attr-value>

//  Load Liquid procedures
// -----------------------------------------------------------------------------
{% capture load_attributes %}themes/{{site.template.name}}/procedures/global/attributes_loader.proc{%endcapture%}

// Load page attributes
// -----------------------------------------------------------------------------
{% include {{load_attributes}} scope="global" %}


// Page content
// ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
[role="dropcap"]
Spontanorama, mit dem Format ist alles möglich, denn kein Gast ist
vorherbestimmt. Ralf Schmitz weiß nie, wer als Nächstes durch die Tür kommt.

++++
<div class="video-title">
  <i class="mdib mdi-bs-primary mdib-clock mdib-24px mr-2"></i>
  60+ Minuten Audiozeit
</div>
++++

// Include sub-documents (if any)
// -----------------------------------------------------------------------------
[role="mt-5"]
== Über den Podcast

Während Ralf im Studio ungeduldig wartet, läuft draußen ein Teammitglied
durch die Straßen der Kölner Innenstadt auf der Suche nach Passantinnen
und Passanten, die spontan bereit sind, alles stehen und liegen zu lassen,
um mit Ralf Schmitz für eine Stunde zu quatschen.

[role="mt-4 mb-4"]
[NOTE]
====
Aus Gründen des *Urheberschutzes*, lädt der Audio Player alle Folgen über
die Server von https://earlystudios.com/[Early, {browser-window--new}].
Eine Internetverbindung zum Hören der Podcasts ist daher *zwingend*
erforderlich.

Darüberhinaus finden Sie den Podcast überall da, wo es Podcasts gibt.
Z.B. bei https://podcasts.apple.com/de/podcast/spontanorama/id1741818812[Apple Podcasts, {browser-window--new}]
oder in den Angeboten von https://open.spotify.com/show/1CZ31uaQ6JTwood52CKQ9H[Spotify, {browser-window--new}].
====


[role="mt-5"]
== Episoden

Im Player sind alle Episoden verfügbar, die im Jahr *2024* produziert wurden.

[role="mt-4 mb-5"]
[TIP]
====
Es erscheint *jede Woche Donnerstags* eine neue Folge.
====

// .Spontanorama 2024
// amplitude::spontanorama_2024_compact[role="mt-4 mb-5"]

// lorem:sentences[5]

.Spontanorama 2024
amplitude::spontanorama_2024_large[role="mt-4 mb-8"]

