---
title:                                  SpontanOrama
tagline:                                Podcast mit Ralf Schmitz

date:                                   2024-09-11
#last_modified:                         2024-09-11

description: >
                                        Hier ist alles möglich, denn kein Gast ist vorherbestimmt – Ralf Schmitz weiß
                                        nie, wer als Nächstes durch die Tür tritt. Während er im Studio ungeduldig
                                        wartet, läuft draußen ein Teammitglied durch die Straßen, auf der Suche
                                        nach wildfremden Passantinnen und Passanten, die jetzt in diesem Moment
                                        bereit sind, alles stehen und liegen zu lassen, um spontan mit Ralf zu
                                        quatschen.
keywords: >
                                        SpontanOrama, Podcast, Impro, Ralf Schmitz

categories:                             [ Podcast ]
tags:                                   [ Impro, Ralf Schmitz ]

image:
  path:                                 /assets/image/modules/attics/1920x1280/spontanorama.png
  width:                                1920
  height:                               1200

tts:                                    true
fab_menu_id:                            open_toc                                # default
personalization:                        false
comments:                               false

regenerate:                             false
permalink:                              /pages/public/audio/podcast/spontanorama/

resources:                              [ amplitudejs ]
resource_options:
  - attic:
#     opacity:                          0.5
      padding_top:                      650
      slides:
        - url:                          /assets/image/modules/attics/1920x1280/spontanorama.jpg
          alt:                          SpontanOrama
---

// Page Initializer
// =============================================================================
// Enable the Liquid Preprocessor
:page-liquid:

// Set (local) page attributes here
// -----------------------------------------------------------------------------
// :page--attr:                         <attr-value>

//  Load Liquid procedures
// -----------------------------------------------------------------------------
{% capture load_attributes %}themes/{{site.template.name}}/procedures/global/attributes_loader.proc{%endcapture%}

// Load page attributes
// -----------------------------------------------------------------------------
{% include {{load_attributes}} scope="global" %}

[role="dropcap"]
SpontanOrama. Mit dem Format ist alles möglich, denn kein Gast ist vorherbestimmt.
Ralf Schmitz weiß nie, wer als Nächstes durch die Tür kommt.

mdi:clock-time-five-outline[24px, md-gray mt-4 mb-5 mr-2]
*60+ Minuten* Audiozeit


[role="mt-4"]
== About

Während Ralf im Studio ungeduldig wartet, läuft draußen ein Teammitglied
durch die Straßen der Kölneer Innenstadt auf der Suche nach Passantinnen
und Passanten, die spontan bereit sind, alles stehen und liegen zu lassen,
um mit Ralf Schmitz für eine Stunde zu quatschen.

Der Podcast ist auf allen gängigen Plattformen für Podcast verfügbar wie:

Spotify::
  Die unangefochtene Nummer eins. Spotify bietet nicht nur Musik, sondern
  auch eine riesige Auswahl an Podcasts. Es ist einfach zu bedienen und
  bietet personalisierte Empfehlungen.

Apple Podcasts::
  Die Standard-App für Apple-Nutzer. Hier findest du eine große Auswahl
  an Podcasts, die du direkt auf deinem iPhone, iPad oder Mac hören kannst.

[role="mt-4"]
[TIP]
====
Aus Gründen des Urheberschutzes, werden alle Folgen direkt über das Angebot
der _Spotify_ Podcast-Plattform
https://megaphone.spotify.com/de-DE[Megaphone, {browser-window--new}]
geladen. Daher ist eine Internetverbindung zum Hören des Podcasts
*zwingend* erforderlich.
====


[role="mt-5"]
== Podcasts

Spontanorama ist eine Produktion von Early Studios, die im Mai 2024 gestartet
ist. Im Player sind alle Episoden verfügbar, die bis *September 2024*
produziert wurden. Es erscheint jeden Donnerstag eine neue Folge.

// .Podcast 2024
// amplitude::spontanorama_2024_compact[role="mt-3 mb-5"]

.Spontanorama 2024
amplitude::spontanorama_2024_large[role="mt-4 mb-7"]
