---
title:                                  Stundenhotel
tagline:                                Satire Podcast
date:                                   2024-09-10
#last_modified:                         2024-09-10

description: >
                                        Einmal im Monat trifft sich Dietmar Wischmeyer mit Sparringspartnerin
                                        Tina Voß in "Wischmeyers Stundenhotel", dem satirischen Podcast von
                                        Bremen Zwei.

                                        Pro Podcast-Date liefern sie sich bissige Dialoge zu einem Thema – spontan
                                        und mit teils harten Pointen.
keywords: >
                                        Radio Bremen Zwei, Wischmeyers Stundenhotel, Podcast,
                                        Tina Voß, Dietmar Wischmeyer

categories:                             [ Audio ]
tags:                                   [ Podcast, Tina Voß, Dietmar Wischmeyer ]

image:
  path:                                 /assets/image/module/attic/1920x1280/stundenhotel.jpg
  width:                                1920
  height:                               1200

tts:                                    true
fab_menu_id:                            open_toc                                # default
personalization:                        false
comments:                               false

regenerate:                             false
permalink:                              /pages/public/audio/podcast/stundenhotel/

resources:                              [ amplitudejs, videojs ]
resource_options:
  - attic:
      opacity:                          0.8
      padding_top:                      550
      slides:
        - url:                          //api.ardmediathek.de/image-service/images/urn:ard:image:505bdf228e6943b9?w=448&ch=aa6f24c2e7cf8b36
          alt:                          stundenhotel
          badge:
            type:                       unsplash
            author:                     Bremen 2
            href:                       //ardaudiothek.de/sendung/wischmeyers-stundenhotel/59505860/

---

// Page Initializer
// =============================================================================
// Enable the Liquid Preprocessor
:page-liquid:

// Set (local) page attributes here
// -----------------------------------------------------------------------------
// :page--attr:                         <attr-value>
:time-num--string:                      60+
:time-de--string:                       Minuten
:time-de--description:                  Audiozeit

//  Load Liquid procedures
// -----------------------------------------------------------------------------
{% capture load_attributes %}themes/{{site.template.name}}/procedures/global/attributes_loader.proc{%endcapture%}

// Load page attributes
// -----------------------------------------------------------------------------
{% include {{load_attributes}} scope="global" %}

// Page content
// ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
[role="dropcap"]
Einmal im Monat trifft sich Dietmar Wischmeyer mit Sparringspartnerin
Tina Voß im Wischmeyers Stundenhotel, dem satirischen Podcast von
Bremen Zwei.

Beim Podcast-Date liefern sie sich bissige Dialoge zu einem Thema.
Spontan und teils mit harten Pointen.

[subs=attributes]
++++
<div class="video-title">
  <i class="mdi mdi-gray mdi-clock-time-five-outline mdi-24px mr-2"></i>
  {time-num--string} {time-de--string} {time-de--description}
</div>
++++

// Include sub-documents (if any)
// -----------------------------------------------------------------------------
[role="mt-5"]
== Episoden

_Dietmar Wischmeyer_ bezeichnet sich selbst als B-Promi und findet das gut
und richtig so. Dennoch werden sehr viele Menschen in Deutschanld Wischmeyer
kennen. Einer großen Fernsehöffentlichkeit ist er mit Beiträgen zur Rubrik
link:https://www.youtube.com/watch?v=KBNqwb1TqMw/[Logbuch der Bekloppten und Bescheuerten, {browser-window--new}]
der
link:https://www.zdf.de/comedy/heute-show/[ZDF-Heute Show, {browser-window--new}]
bekannt geworden.

Promi-Podcasts können so eine Sache sein. Glühende Verehrer*innen eines Promis
werden wahrschinlich die jeweiligen Podcasts sehr mögen - für alle anderen
nicht unbedingt.

Dietmar Wischmeyer ist ein kluger Kopf - jedoch mit recht ausgeprägten Attitüde
eines Intellektuellen. Er hält sein Wissen noch seine persönliche Meinung
hinter dem Berg. So manche werden ihn als Klugscheisser empfinden und seine
Ansichten nicht unbedingt teilen.

Die Besonderheit an diesen Promi-Podcast ist der *Dauer-Gast* _Tina Voß_,
die sich in jeder Folge tapfer den Kommentaren und Bemerkungen Wischmeyer's
zum jeweiligen Thema stellt.

Dank der beiden Protagonisten, die sich jeder in ihrer Weise auf das Thema
des Posdcast vorbereiten, enstehen sehr unterhaltsame Gespräche wie amüsante
Wortgefechte.

Ein Thema ist in jedem Podcast Programm: *Untenrum*. Zwischenmenschliches von
Frauen und Männern, Norddeutsch das *Wemsen*, findet immer seinen Platz.

[role="mt-4 mb-5"]
[TIP]
====
Es erscheint in der *ersten Woche jeden Monats* eine neue Folge. Der Tag des
neuen Podcasts ist unbekannt. Der genaue Tag wird von einem einäugigen
Blinden mit runden Würfeln ermittelt: Das kann schon mal etwas brauchen.
====

[role="mt-5"]
=== 2025

Im Player sind alle Episoden verfügbar, die im *Jahr 2025* produziert wurden.

[role="mt-4 mb-5"]
[NOTE]
====
Aus Gründen des Urheberschutzes, lädt der Audio Player alle Folgen direkt
über das Angebot der link:https://www.ardaudiothek.de/[ARD Audiothek, {browser-window--new}].
Daher ist eine Internetverbindung zum Hören *zwingend* erforderlich.
====

.Stundenhotel 2025
amplitude::stundenhotel_2025_large[role="mt-4 mb-5"]


[role="mt-5"]
=== 2024

Im Player sind alle Episoden verfügbar, die im *Jahr 2024* produziert wurden.
Episonen aus voherigen Jahren findedt man in den folgenden Abschnitten.

[role="mt-4 mb-5"]
[NOTE]
====
Aus Gründen des Urheberschutzes, lädt der Audio Player alle Folgen direkt
über das Angebot der link:https://www.ardaudiothek.de/[ARD Audiothek, {browser-window--new}].
Daher ist eine Internetverbindung zum Hören *zwingend* erforderlich.
====

.Stundenhotel 2024
amplitude::stundenhotel_2024_large[role="mb-5"]


[role="mt-5"]
=== 2023

Im Player sind alle Episoden verfügbar, die im *Jahr 2023* produziert wurden.

[role="mt-4 mb-5"]
[NOTE]
====
Aus Gründen des Urheberschutzes, lädt der Audio Player alle Folgen direkt
über das Angebot der link:https://www.ardaudiothek.de/[ARD Audiothek, {browser-window--new}].
Daher ist eine Internetverbindung zum Hören *zwingend* erforderlich.
====

.Stundenhotel 2023
amplitude::stundenhotel_2023_large[role="mb-8"]


// [role="mt-5"]
// === 2022

// Im Player sind alle Episoden verfügbar, die im *Jahr 2022* produziert wurden.

// .Stundenhotel 2022
// amplitude::stundenhotel_2022_large[role="mt-4 mb-8"]

