---
title:                                  Wischmeyers Stundenhotel
tagline:                                Satire Podcast

date:                                   2024-09-10
#last_modified:                         2024-09-10

description: >
                                        Einmal im Monat trifft sich Dietmar Wischmeyer mit Sparringspartnerin
                                        Tina Voß in "Wischmeyers Stundenhotel", dem satirischen Podcast von
                                        Bremen Zwei.

                                        Pro Podcast-Date liefern sie sich bissige Dialoge zu einem Thema – spontan
                                        und mit teils harten Pointen.
keywords: >
                                        Radio Bremen Zwei, Wischmeyers Stundenhotel, Podcast,
                                        Tina Voß, Dietmar Wischmeyer

categories:                             [ Podcast ]
tags:                                   [ Radio Bremen Zwei, Tina Voß, Dietmar Wischmeyer ]

image:
  path:                                 /assets/image/modules/attics/1920x1280/stundenhotel.jpg
  width:                                1920
  height:                               1200

tts:                                    true
fab_menu_id:                            open_toc                                # default
personalization:                        false
comments:                               false

regenerate:                             false
permalink:                              /pages/public/audio/podcast/stundenhotel/

resources:                              [ amplitudejs ]
resource_options:
  - attic:
#     opacity:                          0.5
      padding_top:                      650
      slides:
        - url:                          /assets/image/modules/attics/1920x1280/stundenhotel.jpg
          alt:                          stundenhotel
---

// Page Initializer
// =============================================================================
// Enable the Liquid Preprocessor
:page-liquid:

// Set (local) page attributes here
// -----------------------------------------------------------------------------
// :page--attr:                         <attr-value>

//  Load Liquid procedures
// -----------------------------------------------------------------------------
{% capture load_attributes %}themes/{{site.template.name}}/procedures/global/attributes_loader.proc{%endcapture%}

// Load page attributes
// -----------------------------------------------------------------------------
{% include {{load_attributes}} scope="global" %}

[role="dropcap"]
Einmal im Monat trifft sich Dietmar Wischmeyer mit Sparringspartnerin
Tina Voß in "Wischmeyers Stundenhotel", dem satirischen Podcast von
Bremen Zwei.

Beim Podcast-Date liefern sie sich bissige Dialoge zu einem Thema.
Spontan und teils mit harten Pointen.

mdi:clock-time-five-outline[24px, md-gray mt-4 mb-5 mr-2]
*60+ Minuten* Audiozeit


[role="mt-4"]
== Über den Podcast

lorem:sentences[5]

Der Podcast ist bei der ARD (Mediathek) und auf allen gängigen Plattformen
für Podcasts verfügbar wie:

Spotify::
  https://open.spotify.com/intl-de/[Spotify, {browser-window--new}]
  ist die unangefochtene Nummer eins. Spotify bietet nicht nur Musik,
  sondern auch eine riesige Auswahl an Podcasts. Es ist einfach zu bedienen
  und bietet personalisierte Empfehlungen.

Apple Podcasts::
  https://www.apple.com/de/apple-podcasts/[Apple Podcasts, {browser-window--new}]
  ist die Standard-Plattform für Apple-Nutzer. Hier findest du eine große Auswahl
  an Podcasts, die du direkt auf deinem iPhone, iPad oder Mac hören kannst.


[role="mt-4"]
[TIP]
====
Aus Gründen des Urheberschutzes, werden alle Folgen direkt über das Angebot
der _ARD Mediathek_ geladen. Daher ist eine Internetverbindung zum Hören des
Podcasts *zwingend* erforderlich.
====


[role="mt-5"]
== Podcasts

lorem:sentences[5]

// Spontanorama ist eine Produktion von Early Studios, die im Mai 2024 gestartet
// ist. Im Player sind alle Episoden verfügbar, die bis *September 2024*
// produziert wurden. Es erscheint jeden Donnerstag eine neue Folge.

.Stundenhotel 2024
amplitude::stundenhotel_2024_large[role="mt-4 mb-7"]
