---
title:                                  Wischmeyers Stundenhotel
tagline:                                Satire Podcast

date:                                   2024-09-10
#last_modified:                         2024-09-10

description: >
                                        Einmal im Monat trifft sich Dietmar Wischmeyer mit Sparringspartnerin
                                        Tina Voß in "Wischmeyers Stundenhotel", dem satirischen Podcast von
                                        Bremen Zwei.

                                        Pro Podcast-Date liefern sie sich bissige Dialoge zu einem Thema – spontan
                                        und mit teils harten Pointen.
keywords: >
                                        Radio Bremen Zwei, Wischmeyers Stundenhotel, Podcast,
                                        Tina Voß, Dietmar Wischmeyer

categories:                             [ Audio ]
tags:                                   [ Podcast, Tina Voß, Dietmar Wischmeyer ]

image:
  path:                                 /assets/image/modules/attics/1920x1280/stundenhotel.jpg
  width:                                1920
  height:                               1200

tts:                                    true
fab_menu_id:                            open_toc                                # default
personalization:                        false
comments:                               false

regenerate:                             false
permalink:                              /pages/public/audio/podcast/stundenhotel/

resources:                              [ amplitudejs ]
resource_options:
  - attic:
#     opacity:                          0.5
      padding_top:                      550
      slides:
        - url:                          /assets/image/modules/attics/1920x1280/stundenhotel.jpg
          alt:                          stundenhotel
---

// Page Initializer
// =============================================================================
// Enable the Liquid Preprocessor
:page-liquid:

// Set (local) page attributes here
// -----------------------------------------------------------------------------
// :page--attr:                         <attr-value>
:time-num--string:                      60+
:time-de--string:                       Minuten
:time-de--description:                  Audiozeit

//  Load Liquid procedures
// -----------------------------------------------------------------------------
{% capture load_attributes %}themes/{{site.template.name}}/procedures/global/attributes_loader.proc{%endcapture%}

// Load page attributes
// -----------------------------------------------------------------------------
{% include {{load_attributes}} scope="global" %}

// Page content
// ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
[role="dropcap"]
Einmal im Monat trifft sich Dietmar Wischmeyer mit Sparringspartnerin
Tina Voß in "Wischmeyers Stundenhotel", dem satirischen Podcast von
Bremen Zwei.

Beim Podcast-Date liefern sie sich bissige Dialoge zu einem Thema.
Spontan und teils mit harten Pointen.

[subs=attributes]
++++
<!-- div class="video-title">
  <i class="mdib mdi-bs-primary mdib-clock mdib-24px mr-2"></i>
  60+ Minuten Audiozeit
</div -->

<div class="video-title">
  <i class="mdi mdi-gray mdi-clock-time-five-outline mdi-24px mr-2"></i>
  {time-num--string} {time-de--string} {time-de--description}
</div>
++++

// Include sub-documents (if any)
// -----------------------------------------------------------------------------
[role="mt-5"]
[TIP]
====
Aus Gründen des Urheberschutzes, werden alle Folgen direkt über das Angebot
der _ARD Mediathek_ geladen. Daher ist eine Internetverbindung zum Hören des
Podcasts *zwingend* erforderlich.
====

[role="mt-5"]
== Episoden 2024

Im Player sind alle Episoden verfügbar, die bis *September 2024*
produziert wurden. Es erscheint jeden Monat eine neue Folge.

.Stundenhotel 2024
amplitude::stundenhotel_2024_large[role="mt-4 mb-7"]
