---

title:                                  Trucker Epos
tagline:                                TV Serie aus den 1980ern

date:                                   2024-09-01
#last_modified:                         2023-01-01

description: >
                                        Die beiden Truckerfahrer Franz Meersdonk (Manfred Krug) und
                                        Günther Willers (Rüdiger Kirschstein) fahren Terminfracht durch die ganze Welt.
                                        Bei ihren abenteuerlichen Touren treffen sie nicht nur auf fremde Bräuche
                                        und Sitten, sondern auch auf viele zwielichtige Typen, Diebe und
                                        Halsabschneider.
keywords: >
                                        Kultserie, Fernsehserie, TV, Trucker Epos,
                                        Manfred Krug, Rüdiger Kirschstein

categories:                             [ Video ]
tags:                                   [ TV Serie, Trucker Epos ]

image:
  path:                                 /assets/image/module/attic/1920x1280/auf-achse.png
  width:                                1920
  height:                               1200

tts:                                    true
fab_menu_id:                            open_toc
comments:                               false
regenerate:                             false
permalink:                              /pages/public/video/serien/auf-achse/

resources:                              [
                                          gallery, lightgallery, masonry,
                                          rouge, videojs, vimeo-player
                                        ]
resource_options:
  - toccer:
      collapseDepth:                    3
  - attic:
      padding_top:                      550
      slides:
        - url:                          /assets/image/module/attic/1920x1280/auf-achse.png
          alt:                          Auf Achse
---

// Page Initializer
// =============================================================================
// Enable the Liquid Preprocessor
:page-liquid:

// Set (local) page attributes here
// -----------------------------------------------------------------------------
// :page--attr:                         <attr-value>

//  Load Liquid procedures
// -----------------------------------------------------------------------------
{% capture load_attributes %}themes/{{site.template.name}}/procedures/global/attributes_loader.proc{%endcapture%}

// Load page attributes
// -----------------------------------------------------------------------------
{% include {{load_attributes}} scope="global" %}


// Page content
// ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
[role="dropcap"]
Die beiden Truckerfahrer Franz Meersdonk und Günther Willers fahren
Terminfracht durch die ganze Welt.

Bei ihren abenteuerlichen Touren treffen sie nicht nur auf fremde Bräuche
und Sitten, sondern auch auf viele zwielichtige Typen, Diebe und
Halsabschneider.

// mdi:clock-time-five-outline[24px, md-gray mt-4 mb-5 mr-2]
// *45+ Minuten* Videozeit

++++
<div class="video-title">
  <i class="mdib mdi-bs-primary mdib-clock mdib-24px mr-2"></i>
  45+ Minuten Videozeit
</div>
++++

// Include sub-documents (if any)
// -----------------------------------------------------------------------------
[role="mt-5"]
== Über die Serie

Quelle: https://de.wikipedia.org/wiki/Auf_Achse_(Fernsehserie)[Wikipedia, {browser-window--new} ]

Die Idee zu der Fernfahrer-Serie stammt von Georg Feil. Das Projekt wurde dann
zusammen mit dem Regisseur Hartmut Griesmayr sowie dem Kameramann
Joseph Vilsmaier geplant. Die Produktion lief von 1978 bis 1996 und startete
ab dem Jahr 1980 im Vorabendprogramm der ARD. Es wurden insgesamt 86 Folgen
produziert.

Die Besetzung der Hauptrollen war dabei nicht ganz einfach. Gesucht wurden zwei
Schauspieler, die LKW fahren konnten. Nachdem zunächst eine andere Besetzung
für die Hauptrolle des Franz Meersdonk geplant war, wurde schließlich
Manfred Krug engagiert, der gerade aus der DDR in die Bundesrepublik
ausgereist war.

Als dessen Gegenpart Günther Willers verpflichtete man Rüdiger Kirschstein.
Um das Alltagsleben der Fernfahrer möglichst realitätsnah zu zeigen, wurde
eigens der erfahrene Fernfahrer Engelbert Teischl(Orient-Berti) aus Freising
als Berater engagiert.

Teischl fuhr selbst regelmäßig in den Nahen Osten. Er hatte die Aufgabe,
die Crew dahingehend zu instruieren, dass die Bewegungen, Abläufe und Rituale
der Fernfahrer in der Serie echt aussahen. Entsprechend wurde im Konzept zu
dieser Serie Wert darauf gelegt, die Länder, Menschen und Kulturen so zu
zeigen, wie sie sind.

Daher werden die Einheimischen meist in ihrer Landessprache zu hören sein und
keine Untertitel angeboten. Man setzte grundsätzlich auf Statisten und oft auf
Schauspieler aus dem jeweiligen Land.


[role="mt-5"]
[[erste-staffel]]
== Erste Staffel (1980)

Die erste Staffel ist wohl die *kultigste*. Spannende Stories, die man den
Schauspielern abnimmt. Es werden Geschichten so erzählt, dass man glauben
kann das die Länder, Menschen und Kulturen so sind - wie sie sind.

// ++++
// <div class="youtube-player bottom">
//   Auf Achse
//   <video
//     id="i8oqdcmAv4Y"
//     class="video-js vjs-theme-uno"
//     controls
//     width="640" height="360"
//     poster="//img.youtube.com/vi/i8oqdcmAv4Y/maxresdefault.jpg"
//     alt="Vollgas"
//     aria-label="Vollgas"
//     data-setup='{
//       "fluid" : true,
//       "techOrder": [
//         "youtube", "html5"
//       ],
//       "sources": [{
//         "type": "video/youtube",
//         "src": "//youtube.com/watch?v=i8oqdcmAv4Y"
//       }],
//       "controlBar": {
//         "pictureInPictureToggle": false,
//         "volumePanel": {
//           "inline": false
//         }
//       }
//     }'
//   > </video>
// </div>
// ++++

.Staffel 1
gallery::auf_achse_s01[role="mt-4 mb-4"]


// [role="mt-5"]
// [[zweite-staffel]]
// == Zweite Staffel (1983/84)

// Videos created by a digicam or a mobile can be played by J1 Template using
// the lightGallery integration. Present videos you have made at it's best.
//
// .Local MP4 Video
// gallery::jg_video_html5[role="mt-4 mb-5"]


// [role="mb-7"]
// In Vorbereitung.

// .Staffel 2
// gallery::auf_achse_s02[role="mt-5 mb-4"]
