---
title:                                  Sträter
tagline:                                Comedy Show mit Gästen
title_extention:                        Comedy Show mit Gästen


date:                                   2024-09-14
#last_modified:                         2023-01-01

description: >
                                        Torsten Sträter lädt mit seiner Show zu einem Abend unter Freunden
                                        in Köln ein. Nach einem Stand-up-Teil heißt er im Verlauf der Show
                                        Gästen willkommen.

keywords:                               TV, Show, Sträter, Torsten Sträter

categories:                             [ Video ]
tags:                                   [ Show, Torsten Sträter ]

image:
  path:                                 /assets/image/leute/torsten-straeter.jpg
  width:                                1280
  height:                               720

tts:                                    true
fab_menu_id:                            open_toc
comments:                               false
regenerate:                             false
permalink:                              /pages/public/video/show/straeter/

resources:                              [ videojs ]
resource_options:
  - attic:
      padding_top:                      550
      slides:
        - url:                          /assets/image/leute/torsten-straeter.jpg
          alt:                          Torsten Sträter
---

// Page Initializer
// =============================================================================
// Enable the Liquid Preprocessor
:page-liquid:

// Set (local) page attributes here
// -----------------------------------------------------------------------------
// :page--attr:                         <attr-value>

//  Load Liquid procedures
// -----------------------------------------------------------------------------
{% capture load_attributes %}themes/{{site.template.name}}/procedures/global/attributes_loader.proc{%endcapture%}

// Load page attributes
// -----------------------------------------------------------------------------
{% include {{load_attributes}} scope="global" %}


// Page content
// ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
[role="dropcap"]
Torsten Sträter lädt mit seiner Show zu *einem Abend unter Freunden* in Köln
(Mülheimer Hafen) ein. Nach einem Stand-up-Teil heißt er im Verlauf der Show
Gästen willkommen.

++++
<div class="video-title">
  <i class="mdib mdi-bs-primary mdib-clock mdib-24px mr-2"></i>
  45+ Minuten Videozeit
</div>
++++

// Include sub-documents (if any)
// -----------------------------------------------------------------------------
[role="mt-5"]
== Über die Show

Torsten Sträter lädt mit seiner Show zu *einem Abend unter Freunden* in Köln
(Mülheimer Hafen) ein. Nach einem Stand-up-Teil heißt er im Verlauf der Show
Gästen willkommen.

In der Rubrik *Hausbesuche* trifft der Kabarettist außerdem auf skurrile
Leute aus dem sogenannten *echten Leben*, die ihm etwas zu sagen oder zu
zeigen haben.

[role="mt-4"]
[TIP]
====
Aus Gründen des Urheberschutzes, werden alle Videos direkt über das Angebot
der _ARD Mediathek_ oder über die Plattform _YouTube_ geladen. Daher ist eine
Internetverbindung zum Ansehen der Videos *zwingend* erforderlich.
====


[role="mt-5"]
[[straeter-marc-uwe-kling]]
== Abend mit Autor Marc-Uwe Kling

Sexualität ist so ein Thema. Eltern werden im Laufe der Zeit sehrwohl zu
Spezialisten in Fragen der Erziehung. Dennoch sind Eltern keine Pädagogen.

Wenn es um Wissen geht, dass man seinen Kindern zu Themen der Sexualität
vermitteln möchte (oder muss), kann das auch gewaltig schiefgehen. Sehen Sie
einen amüsanten Rohrkrepierer zum Thema *Aufklärung*. Gelesen von Marc-Uwe Kling
und Torsten Sträter.

.Gast Marc-Uwe Kling
// videojs:://wdrmedien-a.akamaihd.net/medp/ondemand/weltweit/fsk0/282/2823650/2823650_48912942.mp4[start="00:32:30" poster="/assets/video/gallery/straeter-marc-uwe-kling.jpg" role="mt-4 mb-5"]
youtube::YT-AFO8Em_8[start="00:43:42" poster="/assets/video/gallery/straeter-marc-uwe-kling.jpg" role="mt-4 mb-5"]


[role="mt-5"]
[[straeter-laura-wotorra]]
== Abend mit Moderation Laura Wontorra

Laura Wontorra erzählt Torsten Stäter über ihre Karriere, Kochkünste und über
Lampenfieber. Gemeinsam kommentieren sie sportliche Wettkämpfe der etwas
anderen Art.

.Gast Laura Wotorra
videojs:://wdrmedien-a.akamaihd.net/medp/ondemand/weltweit/fsk0/310/3104436/3104436_57034391.mp4[start="00:04:00" poster="/assets/video/gallery/straeter-laura-wontorra.jpg" role="mt-4 mb-5"]
// youtube::dISStyvJDCA[start="00:04:00" poster="/assets/video/gallery/straeter-laura-wontorra.jpg" role="mt-4 mb-5"]


[role="mt-5"]
[[straeter-wladimir-kaminer]]
== Abend mit Autor Wladimir Kaminer

Zu Gast ist der Schriftsteller Wladimir Kaminer. Die beiden präsentieren
ungewöhnliche (lokal) Nachrichten aus aller Welt.

.Gast Wladimir Kaminer
// videojs:://wdrmedien-a.akamaihd.net/medp/ondemand/weltweit/fsk0/292/2921065/2921065_51538185.mp4[start="00:04:10" poster="/assets/video/gallery/straeter-wladimir-kaminer.jpg" role="mt-4 mb-5"]
youtube::Z6MzsZXhMZs[poster="/assets/video/gallery/straeter-wladimir-kaminer.jpg" role="mt-4 mb-5"]


[role="mt-5"]
[[straeter-ralph-ruthe]]
== Abend mit Cartoonist Ralph Ruthe

Zu Gast ist der Zeichner und Cartoonist Ralph Ruthe. Lustige Sprüche,
nostalgische Texte und brillante *Cartoons* von Ralph Ruthe.

.Gast Ralph Ruthe
videojs:://wdrmedien-a.akamaihd.net/medp/ondemand/weltweit/fsk0/292/2925505/2925505_51633160.mp4[start="00:03:00" poster="/assets/video/gallery/straeter-ralph-ruthe.jpg" role="mt-4 mb-5"]


[role="mt-5"]
== Rubriken

lorem:sentences[5]

[role="mt-4"]
=== Tino Bomelino

Comedian Tino Bomelino, im *richtigen* Leben _Tino Hartmann_ (geboren 1985 in
Ost-Berlin), ist eigentlich studierter Informatiker (Universität Stuttgart).
Noch in Stuttgart hatte er seine ersten Poetry-Slam Auftritte. Und das
merkt man: Er kann Geschichten und diese in Sprache umsetzen. Er ist ein heller
Kopf mit analytischen Fähigkeiten; mit Tendenz zum Schrägen.

Seine Geschichten lassen immer die Frage offen: Wie kommt man auf darauf?
Das Gute: Eine Antwort ist egal. Dafür sind seine Storys zu gut.

Die kuriosen Präsentation von Tino Bomelino sind fester Bestandteil der
Sträter Show. Ziel der Präentationen scheint zu sein: Ideen und Ratschläge
zugeben, die niemand wissen wollte.

Der Comedian erklärt an einer Flip-Chart sehr anschaulich Ideen, Konzepte
und Projekte für das Leben von Menschen an sich; und im Speziellen. Kleine
Einschränkung: Man wird niemals irgendetwas von diesem Wissen brauchen. Noch
auch nur eine dieser Ideen anwenden oder gar umsetzen wollen.

Wie so häufig im richtigen Leben. So manches kennt man aus dem Beruf oder
von Freunden: Gut gemeint, aber ...

[role="mt-5"]
[[tino-bomelino-unsterblichkeit]]
==== Unsterblichkeit
//Wie werde ich unsterblich? – Tino Bomelino | STRÄTER Folge 20

Tino Bomelino erklärt, was alles anders wäre, wären wir unsterblich. Und gibt
wertvolle Ratschläge, wenn es soweit ist.

Tino sagt: Sollte man wissen, bevor es soweit ist.

.Tino Bomelino · Unsterblichkeit
videojs:://wdrmedien-a.akamaihd.net/medp/ondemand/weltweit/fsk0/310/3104436/3104436_57034391.mp4[start="00:33:20" poster="/assets/video/gallery/straeter-tino-bomelino.jpg" role="mt-4 mb-5"]
//youtube::7HdwlymdK-U[poster="/assets/video/gallery/straeter-tino-bomelino.jpg" role="mt-4 mb-5"]

[role="mt-5"]
[[tino-bomelino-hobbys]]
==== Beliebte Hobbys

Tino Bomelino präsentiert die beliebtesten Hobbys. Falls jemand noch kein
Hobby hat und eines sucht, kann diese Präsentation bei der Suche nach
einem geeigneten Hobby helfen.

Hobby finden mit Tino - oder auch nicht.

.Tino Bomelino · Die beliebtesten Hobbys
videojs:://wdrmedien-a.akamaihd.net/medp/ondemand/weltweit/fsk0/292/2921065/2921065_51538185.mp4[start="00:34:49" poster="/assets/video/gallery/straeter-tino-bomelino.jpg" role="mt-4 mb-5"]

[role="mt-5"]
[[tino-bomelino-erfolgs-kurs]]
==== Erfolgs-Kurs
//Tino Bomelino stellt seinen Erfolgskurs vor! | STRÄTER Folge 19

Tino Bomelino präsentiert wie man sein Leben optimieren kann. Ein Thema das
sicher viele beschäftigt. Zeit ist Geld, das Konzept des GlobalTurbo für das
Einsparen von Zeit ist revolutionär. Tino präsentiert seinen Erfolgskurs für
alle, die Bock auf Erfolg haben. Eines Vorab: Morgens ganz entspannt Kaffee
machen? Der absolut falsche Weg!

Tino erklärt, wie Erfolg richtig geht.

.Tino Bomelino · Erfolgs-Kurs
videojs:://wdrmedien-a.akamaihd.net/medp/ondemand/weltweit/fsk0/292/2925505/2925505_51633160.mp4[start="00:33:18" poster="/assets/video/gallery/straeter-tino-bomelino.jpg" role="mt-4 mb-5"]
// youtube::gGdzc1Pwfps[poster="/assets/video/gallery/straeter-tino-bomelino.jpg" role="mt-4 mb-5"]

[role="mt-5"]
[[tino-bomelino-unklare-gegenteile]]
==== Unklare Gegenteile
//Ausschnitt aus STRÄTER Folge 23 vom 26.10.2023.

Wissen ist Macht; dass weis wohl jeder. Würde es Warnhinweise für die
Präsentation von Tino Bomelino geben, dann vielleicht soetws: Kann Teile
von Wissen enthalten. Manche Gegenteile sind ganz offensichtlich, Tino hat
Beispiele von Gegenteilen mitgebracht, die weniger bekannt oder unklar sind,
aber schon wichtig sein können.

Lernen für's Leben mit Tino.

.Tino Bomelino · Unklare Gegenteile
youtube::SxiubinEdfs[poster="/assets/video/gallery/straeter-tino-bomelino.jpg" role="mt-4 mb-5"]

[role="mt-5"]
[[tino-bomelino-unnötige-superhelden]]
==== Unnötige Superhelden
//Tino Bomelino stellt unnötige Superhelden vor | STRÄTER Folge 21

Was kann die *Enten-Frau*? Wie kommuniziert *Telepathio*? Warum kommt
die *Teleportier-Frau* immer zu spät? Und was findet *Super-Mann* nicht
super?

Thema Superhelden unklar? Tino gibt Antworten.

.Tino Bomelino · Unnötige Superhelden
youtube::Is4R8H0dtlA[poster="/assets/video/gallery/straeter-tino-bomelino.jpg" role="mt-4 mb-5"]

[role="mt-5"]
[[tino-bomelino-geschäftsideen]]
==== Geschäftsideen
//Tino Bomelino – Geschäftsideen für Torsten Sträter & Harald Schmidt | STRÄTER Folge 22

Käse mit Pizza im Rand, ein Ausmalbuch für Erwachsene. Eine Tiervermietung und
ein Pyramiden-Bastelplan, der dich und deine Freunde garantiert nicht in ein
Pyramiden-System stürzen wird. Tino präsentiert viele gute Ideen für die
Selbständigkeit auf die man nicht (unbedingt) kommt.

Durchstarten im eigenen Business - mit Tino.

.Tino Bomelino · Geschäftsideen
youtube::yQ1jeCUmV0c[poster="/assets/video/gallery/straeter-tino-bomelino.jpg" role="mt-4 mb-5"]

[role="mb-7"]
lorem:sentences[5]
