---
title:                                  Spontanorama
tagline:                                Podcast mit Ralf Schmitz und Gästen

#date:                                  2024-05-23
#last_modified:                         2024-05-23

description: >
                                        Hier ist alles möglich, denn kein Gast ist vorherbestimmt – Ralf Schmitz weiß
                                        nie, wer als Nächstes durch die Tür tritt. Während er im Studio ungeduldig
                                        wartet, läuft draußen ein Teammitglied durch die Straßen der Innenstadt von
                                        Köln, auf der Suche nach Passanten, die bereit sind alles stehen und liegen
                                        zu lassen um spontan mit Ralf zu quatschen.
keywords: >
                                        Spontanorama, Podcast, Impro, Ralf Schmitz

categories:                             [ Audio ]
tags:                                   [ Podcast, Impro ]

image:
  path:                                 /assets/image/modules/attics/1920x1280/spontanorama.jpg
  width:                                1920
  height:                               1200

group:                                  Featured
#series:                                Featured

tts:                                    true
fab_menu_id:                            default                                 # open_toc
comments:                               false
regenerate:                             false

resources:                              []
resource_options:
  - attic:
#     opacity:                          0.5
      padding_top:                      650
      slides:
        - url:                          /assets/image/modules/attics/1920x1280/spontanorama.jpg
          alt:                          spontanorama
---

// Page Initializer
// =============================================================================
// Enable the Liquid Preprocessor
:page-liquid:

// Set (local) page attributes here
// -----------------------------------------------------------------------------
// :page--attr:                         <attr-value>
:url-player--spontanorama-2024:         /pages/public/audio/podcast/spontanorama/#spontanorama

// Place an excerpt at the most top position
// -----------------------------------------------------------------------------
[role="dropcap"]
Spontanorama. Mit dem Format ist alles möglich, denn kein Gast ist vorherbestimmt.
Ralf Schmitz weiß nie, wer als Nächstes durch die Tür kommt.

Während er im Studio ungeduldig wartet, läuft draußen ein Teammitglied durch
die Straßen der Innenstadt von Köln. Immer auf der Suche nach Passanten, die
in diesem Moment bereit sind alles stehen und liegen zu lassen um spontan mit
Ralf zu quatschen.

excerpt__end

//  Load Liquid procedures
// -----------------------------------------------------------------------------
{% capture load_attributes %}themes/{{site.template.name}}/procedures/global/attributes_loader.proc{%endcapture%}

// Load page attributes
// -----------------------------------------------------------------------------
{% include {{load_attributes}} scope="global" %}


// Page content
// ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

mdi:clock-time-five-outline[24px, md-gray mr-2 mt-3]
*3 Minuten* Lesezeit


// Include sub-documents (if any)
// -----------------------------------------------------------------------------
[role="mt-5"]
== Über den Podcast

Jede Folge ist eine Überraschung mit einer Mischung aus Lachen,
tiefgründigen Momenten und unerwarteten Geschichten aus Ralfs Leben und
denen seiner Gäste.

Während Ralf im Studio ungeduldig wartet, läuft draußen ein Teammitglied
durch die Straßen der Kölneer Innenstadt auf der Suche nach Passantinnen
und Passanten, die spontan bereit sind, alles stehen und liegen zu lassen,
um mit Ralf Schmitz für eine Stunde zu quatschen.

[role="mb-7"]
Hören Sie rein - es ist ein großer Spaß:
link:{url-player--spontanorama-2024}[Spontanorama 2024, {browser-window--new}].
