---
title:                                  TV Total
tagline:                                Late-Night-Show der 00er Jahre

#date:                                  2024-09-14
#last_modified:                         2023-01-01

description: >
                                        Mitte 1999 startete Late-Night-Show TV Total mit Stefan Raab.
                                        Der Moderator gehörte bald zu den bekanntesten Gesichtern im
                                        deutschen (Privat-)Fernsehen.

keywords:                               TV, Show, TV Total, Stefan Raab

categories:                             [ Video ]
tags:                                   [ Show, Stefan Raab ]

image:
  path:                                 //img.youtube.com/vi/guXJa2qbwfM/maxresdefault.jpg
  width:                                1920
  height:                               1200

group:                                  Featured
#series:                                Featured

tts:                                    true
fab_menu_id:                            open_toc
comments:                               false
regenerate:                             false

resources:                              []
resource_options:
  - attic:
#     opacity:                          0.5
      padding_top:                      550
      slides:
        - url:                          //img.youtube.com/vi/guXJa2qbwfM/maxresdefault.jpg
          alt:                          TV Total
---

// Page Initializer
// =============================================================================
// Enable the Liquid Preprocessor
:page-liquid:

// Set (local) page attributes here
// -----------------------------------------------------------------------------
// :page--attr:                         <attr-value>
:url-video--tv-boxkampf:                /pages/public/video/tv-highlights/tv-total/#raab-vs-halmich

//  Load Liquid procedures
// -----------------------------------------------------------------------------
{% capture load_attributes %}themes/{{site.template.name}}/procedures/global/attributes_loader.proc{%endcapture%}

// Load page attributes
// -----------------------------------------------------------------------------
{% include {{load_attributes}} scope="global" %}


// Page content
// ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
[role="dropcap"]
Mitte 1999 startete die Late-Night-Show TV Total mit Stefan Raab. Der Moderator
gehörte bald zu den bekanntesten Gesichtern im deutschen (Privat-)Fernsehen.

Verrückte Studioaktionen und der konsequente Einsatz kurzer Videoschnipsel
für seine Kommentare wurden zum Markenzeichen der Show.

excerpt__end

// Include sub-documents (if any)
// -----------------------------------------------------------------------------
Raab kommentierte mit scharfer Zunge das aktuelle Tagesgeschehen, spottet über
Ausschnitte aus TV und Internet und begrüßte (mehr oder weniger) Prominente aus
dem deutschen wie internationalen Showbiz auf seinem Gästesessel.

++++
<div class="video-title">
  <i class="mdib mdi-bs-primary mdib-clock mdib-24px mr-2"></i>
  3 Minuten Lesezeit
</div>
++++

// Include sub-documents (if any)
// -----------------------------------------------------------------------------
[role="mt-5"]
== Über die Show

Quellen:

* https://www.fernsehserien.de/tv-total[Fernsehserien, {browser-window--new} ]
* https://de.wikipedia.org/wiki/TV_total[Wikipedia, {browser-window--new} ]

[role="mt-4"]
Die Show und der Moderator Stefan Raab wurden schnell bekannt. Die respektlose
Auseinandersetzung mit Pannen und fragwürdigen Entwicklungen im deutschen
Fernsehen war für die damaligen (TV-)Verhältnisse durchaus bemerkswert.

Rubriken der Show wie die Verleihung des *Raab der Woche* für skurrile
Auftritte in den Medien und *Raab in Gefahr*, bei dem sich der Moderator
diversen Mutproben aussetzte, oder das Studio-Quiz *Blamieren oder kassieren*
trugen zum Erfolg der Sendung bei.

Stefan Raab hatte seiner Zeit das TV Publikum wohl häufig gespalten. Jedoch
eines war immer Gewiss: Hier wird was rausgehauen!

[role="mt-4 mb-7"]
Dieses Event ist und bleibt Kult: &nbsp;
link:{url-video--tv-boxkampf}[TV Boxkampf Raab vs. Halmich, {browser-window--new}].
