---
title:                                  Spontanorama
tagline:                                Mit Ralf Schmitz und Gästen

#date:                                  2024-05-23
#last_modified:                         2024-05-23

description: >
                                        Hier ist alles möglich, denn kein Gast ist vorherbestimmt – Ralf Schmitz weiß
                                        nie, wer als Nächstes durch die Tür tritt. Während er im Studio ungeduldig
                                        wartet, läuft draußen ein Teammitglied durch die Straßen der Innenstadt von
                                        Köln, auf der Suche nach Passanten, die bereit sind alles stehen und liegen
                                        zu lassen um spontan mit Ralf zu quatschen.
keywords: >
                                        Spontanorama, Podcast, Impro, Ralf Schmitz

categories:                             [ Audio ]
tags:                                   [ Podcast, Ralf Schmitz ]

image:
  path:                                 /assets/image/leute/ralf-schmitz.jpg
  width:                                1280
  height:                               720

group:                                  Featured
#series:                                Featured

tts:                                    true
fab_menu_id:                            open_toc
comments:                               false
regenerate:                             false

resources:                              []
resource_options:
  - attic:
#     opacity:                          0.5
      padding_top:                      550
      slides:
        - url:                          /assets/image/leute/ralf-schmitz.jpg
          alt:                          Ralf Schmitz
---

// Page Initializer
// =============================================================================
// Enable the Liquid Preprocessor
:page-liquid:

// Set (local) page attributes here
// -----------------------------------------------------------------------------
// :page--attr:                         <attr-value>
:url-player--spontanorama-2024:         /pages/public/audio/podcast/spontanorama/#episoden



//  Load Liquid procedures
// -----------------------------------------------------------------------------
{% capture load_attributes %}themes/{{site.template.name}}/procedures/global/attributes_loader.proc{%endcapture%}

// Load page attributes
// -----------------------------------------------------------------------------
{% include {{load_attributes}} scope="global" %}


// Page content
// ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
[role="dropcap"]
Spontanorama, der neue Podcast mit Ralf Schmitz. Er führt ungezwungene
Gespräche mit zufälligen Passantinnen und Passenten, die kurz zuvor von
der Straße aufgelesen wurden.

Eine Talkshow mit Unbekannten - im wahrsten Sinne des Wortes.

excerpt__end

// Include sub-documents (if any)
// -----------------------------------------------------------------------------
Jede Folge ist eine Überraschung mit einer Mischung aus Lachen, tiefgründigen
Momenten und unerwarteten Geschichten aus Ralfs Leben und denen seiner Gäste.
Egal, ob es sich um eine ältere Dame handelt, die gerade auf dem Weg zum
Einkaufen war, oder um einen Studenten, der gerade seine Bachelorarbeit
abgegeben hat - es kann jeden treffen.

++++
<div class="video-title">
  <i class="mdib mdi-bs-primary mdib-clock mdib-24px mr-2"></i>
  3 Minuten Lesezeit
</div>
++++


// Include sub-documents (if any)
// -----------------------------------------------------------------------------
[role="mt-5"]
== Über den Podcast

Ralf Schmitz weiß nie, wer als Nächstes durch die Tür tritt. Während er im
Studio ungeduldig wartet, läuft draußen ein Teammitglied durch die Straßen
der Innenstadt von Köln, auf der Suche nach Passanten, die bereit sind alles
stehen und liegen zu lassen um spontan mit Ralf zu quatschen

In dieser einzigartigen Atmosphäre entstehen Gespräche, die nicht nur
unvorhersehbar, sondern auch außerordentlich authentisch sind.

[role="mb-7"]
Hören Sie rein, es ist ein großer Spaß:&nbsp;
link:{url-player--spontanorama-2024}[Spontanorama 2024, {browser-window--new}].
